{{ with .Values.aws_creds }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $.Release.Name }}-auth
data:
  awskey: {{ .awskey | b64enc }}
  awssecret: {{ .awssecret | b64enc }}
  awstoken: {{ .awstoken | b64enc }}
{{- end }}
