apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-auth
data:
  awskey: {{ .Values.aws_creds.awskey | b64enc }}
  awssecret: {{ .Values.aws_creds.awssecret | b64enc }}
  awstoken: {{ .Values.aws_creds.awstoken | b64enc }}
