apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-auth
data:
  awskey: {{ if .Values.aws_creds.awskey }}{{ .Values.aws_creds.awskey | b64enc }}{{- else }}''{{- end }}
  awssecret: {{ if .Values.aws_creds.awssecret }}{{ .Values.aws_creds.awssecret | b64enc }}{{- else }}''{{- end }}
  awstoken: {{ if .Values.aws_creds.awstoken }}{{ .Values.aws_creds.awstoken | b64enc }}{{- else }}''{{- end }}
